# Generated by Django 6.0.3 on 2026-03-23 19:03

import candidatures.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Domaine',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('Licence', 'Licence'), ('Master', 'Master'), ('Ingénieur', 'Ingénieur'), ('Doctorat', 'Doctorat')], max_length=20)),
            ],
            options={
                'verbose_name': 'Niveau',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('Preselected', 'Préselectionné'), ('Selected', 'Sélectionné'), ('Rejected', 'Rejeté')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Statut',
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Wilaya',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('direction', models.TextField()),
                ('universite', models.CharField(max_length=200)),
                ('moyenne', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('duree', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('encadrant', models.CharField(blank=True, max_length=200, null=True)),
                ('theme', models.TextField()),
                ('lettre_motivation_text', models.TextField()),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidatures.domaine')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidatures.niveau')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidatures.statut')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidatures.wilaya')),
            ],
            options={
                'verbose_name': 'Candidature',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cv', 'Curriculum Vitae'), ('lettre', 'Lettre de motivation'), ('releve', 'Relevé de notes')], max_length=20)),
                ('fichier', models.FileField(upload_to=candidatures.models.upload_document)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidatures.candidature')),
            ],
            options={
                'verbose_name': 'Document',
                'unique_together': {('candidature', 'type')},
            },
        ),
    ]
