# Generated by Django 6.0.3 on 2026-03-18 13:25

import candidatures.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.CharField(max_length=20)),
                ('wilaya', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('direction', models.TextField()),
                ('universite', models.CharField(max_length=200)),
                ('domaine', models.CharField(max_length=200)),
                ('niveau', models.CharField(choices=[('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3'), ('Master 1', 'Master 1'), ('Master 2', 'Master 2'), ('Doctorat', 'Doctorat'), ('Ingénieur 1', 'Ingénieur 1'), ('Ingénieur 2', 'Ingénieur 2'), ('Ingénieur 3', 'Ingénieur 3'), ('Ingénieur 4', 'Ingénieur 4'), ('Ingénieur 5', 'Ingénieur 5')], max_length=20)),
                ('moyenne', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('duree', models.CharField(max_length=50)),
                ('date_debut', models.CharField(max_length=20)),
                ('date_fin', models.CharField(max_length=20)),
                ('encadrant', models.CharField(blank=True, max_length=200, null=True)),
                ('theme', models.TextField()),
                ('lettre_motivation_text', models.TextField()),
                ('cv', models.FileField(upload_to=candidatures.models.upload_cv)),
                ('lettre_motivation', models.FileField(upload_to=candidatures.models.upload_lettre)),
                ('releve_notes', models.FileField(upload_to=candidatures.models.upload_releve)),
                ('statut', models.CharField(choices=[('Pending', 'En attente'), ('Selected', 'Sélectionné'), ('Rejected', 'Rejeté'), ('Preselected', 'Présélectionné')], default='Pending', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_soumission'],
            },
        ),
    ]
