# Generated by Django 6.0.3 on 2026-04-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
