# Generated by Django 6.0.3 on 2026-03-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='source',
            field=models.CharField(choices=[('formulaire', 'Formulaire public'), ('admin', 'Ajout manuel admin')], default='formulaire', max_length=20),
        ),
    ]
