# Generated by Django 6.0.3 on 2026-04-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0002_candidature_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='motif_refus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
