# Generated by Django 6.0.3 on 2026-05-31 21:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatures', '0004_alter_evaluation_note_globale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_detecte', models.CharField(blank=True, max_length=200)),
                ('diplome', models.CharField(blank=True, max_length=200)),
                ('universite_detectee', models.CharField(blank=True, max_length=300)),
                ('education', models.TextField(blank=True)),
                ('langues', models.JSONField(default=list)),
                ('projets', models.JSONField(default=list)),
                ('competences', models.JSONField(default=list)),
                ('domaine_detecte', models.CharField(blank=True, max_length=100)),
                ('domaine_confiance', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('resume', models.TextField(blank=True)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse_cv', to='candidatures.candidature')),
            ],
            options={
                'verbose_name': 'Analyse CV',
            },
        ),
        migrations.CreateModel(
            name='AnalyseLettreMotivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clarity_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('motivation_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('personalization_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('formality_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('lexical_richness_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('genericity_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('note_globale', models.DecimalField(decimal_places=1, max_digits=4)),
                ('mention', models.CharField(max_length=20)),
                ('style_prediction', models.CharField(max_length=20)),
                ('style_prediction_fr', models.CharField(max_length=40)),
                ('style_confidence', models.DecimalField(decimal_places=3, max_digits=4)),
                ('style_spectre', models.JSONField()),
                ('style_description', models.TextField(blank=True)),
                ('style_signaux', models.JSONField(default=list)),
                ('word_count', models.IntegerField(default=0)),
                ('ttr', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('ameliorations', models.JSONField(default=dict)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse_lettre', to='candidatures.candidature')),
            ],
            options={
                'verbose_name': 'Analyse lettre de motivation',
            },
        ),
    ]
